"""
READ-ONLY diagnostic — list rows whose stored SVG content looks like it was
generated by `_context_svg` (server/services/content_media_migration.py:94-109)
or `_svg_markup` (scripts/oneoff/repair_math_geometry_homeworks.py:83-140).

These two generators were invoked by the pre-fix broad-substring placeholder
check that incidentally clobbered authored SVGs containing the marker phrases
("Homework diagram" / "Formula diagram" / "Handdrawn diagram") anywhere in
their body. The migration fix in commit 380ec83 and the repair-script fix in
commit c83eb9e prevent FUTURE clobbering — they do nothing for rows that
were already overwritten before those commits landed. This script finds them.

It NEVER writes back. Output is a punch list the author can use to decide
which homeworks need a manual SVG restore (from git history, AI regeneration,
or fresh authoring).

Usage:
    python scripts/oneoff/diagnose_clobbered_svgs.py
    python scripts/oneoff/diagnose_clobbered_svgs.py --subject math-algebra
    python scripts/oneoff/diagnose_clobbered_svgs.py --json   # machine-readable

Exit code: 0 always (this is a report, not a check).
"""
from __future__ import annotations

import argparse
import json
import re
import sqlite3
import sys
from pathlib import Path
from typing import Any, Iterator

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from server.config import DB_PATH  # noqa: E402


# ── fingerprints ─────────────────────────────────────────────────────────────
#
# Both generators emit deterministic markers that authored SVGs are extremely
# unlikely to produce together. We match on the COMBINATION of distinctive
# elements rather than any single attribute — keeps false positives near zero.

# _context_svg(subject, label) — from content_media_migration.py
# Signature: viewBox="0 0 900 540" + role="img" + aria-label="..." +
#            <linearGradient id="bg"> + a specific path data sequence.
_CONTEXT_SVG_RE = re.compile(
    r'viewBox=["\']0 0 900 540["\'][^>]*role=["\']img["\'][^>]*aria-label=["\'][^"\']*["\']'
    r'[\s\S]*?<linearGradient\s+id=["\']bg["\']'
    r'[\s\S]*?<path\s+d=["\']M120 386 L292 184 L464 386 Z["\']',
    re.IGNORECASE,
)

# _svg_markup(subject, label) — from repair_math_geometry_homeworks.py
# Signature: width="900" height="760" + viewBox="0 0 900 760" +
#            <linearGradient id="core"> + <filter id="softShadow"> + the
#            specific "BOSHLASH" eyebrow text.
_FORMULA_CARD_RE = re.compile(
    r'viewBox=["\']0 0 900 760["\']'
    r'[\s\S]*?<linearGradient\s+id=["\']core["\']'
    r'[\s\S]*?<filter\s+id=["\']softShadow["\']'
    r'[\s\S]*?BOSHLASH',
    re.IGNORECASE,
)

# Quick "is this string SVG content" guard — avoids matching binary blobs etc.
_HAS_SVG_OPEN_RE = re.compile(r"<svg\b", re.IGNORECASE)


def _classify(value: str) -> str | None:
    if not _HAS_SVG_OPEN_RE.search(value):
        return None
    if _CONTEXT_SVG_RE.search(value):
        return "context_svg"
    if _FORMULA_CARD_RE.search(value):
        return "formula_card"
    return None


def _walk(node: Any, path: str) -> Iterator[tuple[str, str, str]]:
    """Yield (json_path, fingerprint, snippet) for every SVG-shaped string we
    detect inside `node`. The snippet is the first ~160 chars after the <svg
    opening tag, useful for eyeballing in the report.
    """
    if isinstance(node, dict):
        for key, value in node.items():
            yield from _walk(value, f"{path}.{key}")
        return
    if isinstance(node, list):
        for i, item in enumerate(node):
            yield from _walk(item, f"{path}[{i}]")
        return
    if isinstance(node, str):
        fingerprint = _classify(node)
        if fingerprint:
            open_at = node.lower().find("<svg")
            snippet = node[open_at : open_at + 160].replace("\n", " ")
            yield (path, fingerprint, snippet)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Read-only sweep: flag homeworks whose content_json holds an SVG that "
        "matches the fingerprint of _context_svg or _svg_markup (the two generators that "
        "the pre-fix broad-substring placeholder check used to clobber authored content)."
    )
    parser.add_argument(
        "--subject",
        default=None,
        help="Restrict to a single subject (e.g. math-algebra, geometriya-g7-11). Default: all subjects.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit machine-readable JSON instead of the human report.",
    )
    parser.add_argument(
        "--include-deleted",
        action="store_true",
        help="Also scan soft-deleted (trashed) rows.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    db_path = Path(DB_PATH)
    if not db_path.exists():
        print(f"DB not found: {db_path}", file=sys.stderr)
        return 0

    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row

    where = []
    params: list[Any] = []
    if args.subject:
        where.append("subject = ?")
        params.append(args.subject)
    if not args.include_deleted:
        where.append("deleted_at IS NULL")
    where_sql = (" where " + " and ".join(where)) if where else ""

    rows = con.execute(
        f"select id, subject, title, content_json from homeworks{where_sql} order by id",
        tuple(params),
    ).fetchall()

    findings: list[dict[str, Any]] = []
    for row in rows:
        raw = row["content_json"] or ""
        if not raw:
            continue
        try:
            content = json.loads(raw)
        except json.JSONDecodeError:
            continue
        for path, fingerprint, snippet in _walk(content, "content_json"):
            findings.append(
                {
                    "hw_id": row["id"],
                    "subject": row["subject"],
                    "title": row["title"],
                    "json_path": path,
                    "fingerprint": fingerprint,
                    "snippet": snippet,
                }
            )

    if args.json:
        print(json.dumps({"rows_scanned": len(rows), "findings": findings}, ensure_ascii=False, indent=2))
        return 0

    print(f"DB: {db_path}")
    print(f"Rows scanned: {len(rows)}")
    print(f"Findings:     {len(findings)}")
    if not findings:
        print("\nNo SVGs matching the clobbered-content fingerprint found.")
        return 0

    print(
        "\nThe rows below carry an SVG whose shape matches one of the two generators that the "
        "pre-fix placeholder check used. They MAY have been silently overwritten before commits "
        "380ec83 / c83eb9e landed. Inspect each manually before restoring."
    )
    by_fingerprint: dict[str, int] = {}
    for f in findings:
        by_fingerprint[f["fingerprint"]] = by_fingerprint.get(f["fingerprint"], 0) + 1
    print("\nBreakdown:")
    for fp, n in sorted(by_fingerprint.items()):
        label = {
            "context_svg": "_context_svg (migration generic)",
            "formula_card": "_svg_markup (repair-script formula card)",
        }.get(fp, fp)
        print(f"  {label:<48} {n}")

    print("\nDetails:")
    for f in findings:
        print(f"  - {f['hw_id']}  [{f['subject']}]  {f['fingerprint']}  at  {f['json_path']}")
        print(f"      title:   {f['title']}")
        print(f"      snippet: {f['snippet']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
